### ISSUE TITLE
Multiple "External content" tabs ?

### ISSUE THREAD

**Issue by francoismassart** [jimdrury/geometricpanda#19]
# 🚀 feature request

### Relevant Package
I have a question relative to @geometricpanda/storybook-addon-iframe: can we have multiple "External content" tabs inside a single MDX file ?

Thank you for your reply

**Comment by jimdrury** [comment]
That's a fantastic idea!

I don't know whether storybook could do that within the nav bar - the API isn't great for handling data at that stage of registration, but I could certainly look at integrating a secondary nav bar for additional links if that's any help?

**Comment by francoismassart** [comment]
@geometricpanda that would be great 👍

**Comment by jimdrury** [comment]
Unfortunately, the more I've thought about how to implement this the more I've realised that the storybook api won't allow it
