### ISSUE TITLE
Add default badges

### ISSUE THREAD

**Issue by Tim-arts** [jimdrury/geometricpanda#20]
Hello, are there any default badge styles we can use? I've tried to use "Beta" or some others but they share the same default style

**Comment by jimdrury** [comment]
Hey,
I haven't built any in yet but I'd be happy to look at that this evening. 😃 

Any particular colours you think would be good?

Initially I'm thinking
- Default (black)
- Success (green)
- Info (blue)
- Warning (amber)
- Error (red)

**Comment by Tim-arts** [comment]
That's great! Thanks for your reactivity :D
I was actually thinking about some badges with more specific semantics like:

- **Default** (Background: #EDEFF5, Text: #474D66)
- **Beta** (Background: #D6E0FF, Text: #2952CC)
- **Stable | Released** (Background: #DCF2EA, Text: #317159)
- **Needs revision** (Background: #FFEFD2, Text: #66460D)
- **Obsolete** (Background: #F9DADA, Text: #7D2828)
- **Experimental | WIP** (Background: #E7E4F9, Text: #6E62B6)
- **Deprecated** (Background: #F8E3DA, Text: #85462B)

![badges](https://user-images.githubusercontent.com/10064887/127344581-be721645-307e-4bfd-841e-185ee3abc5cb.png)

What do you think?

**Comment by jimdrury** [comment]
Yeah i like it, I'll get them built in shortly - of course with the ability to be customised if needed

**Comment by jimdrury** [comment]
@Tim-arts i've just released this at part of 0.0.4, let me know how you get on :-)

**Comment by Tim-arts** [comment]
Thank you very much, looking at this right now!

**Comment by Tim-arts** [comment]
Do you think it would be possible to let the user customize the overall look a bit more? Like being able to toggle the border, use a custom border-radius, toggle uppercase, etc... By the way the key "contrast" property matches to the background property inside the CSS, maybe it would have a sense to rename it as well?

Anyway that's great already, thank you for taking that issue into consideration!

**Comment by jimdrury** [comment]
Yeah I've thinking about how best to do this

The border actually adds value if people opt for a white or transparent background colour.

But for customising, I'm thinking maybe the solution sits with css custom properties - I'm not the greatest fan of CSS in JS these days.

I guess the options are:
- Expose more theme properties to the config object
- Have a style block inside the config object which gets passed to the inner styled component
- Have a suite of custom properties which get generated for each badge ID with defaults, allowing the user to import css... added benefits include light/dark mode config.

**Comment by Tim-arts** [comment]
The first one will become more and more heavy depending on the level of customization the user wants to give
I'm not a big fan of having style in HTML and I'd prefer to separate Template/Style and Logic apart (but maybe I misunderstood this one)
So I have a preference for the last one since it allows the user to easily customize according to its needs, that also seems to be the more maintenable one

**Comment by jimdrury** [comment]
Hey sorry I just realised it read like I meant an actual <style> tag. Sorry I meant like a style object within the config object.

But yeh I'm leaning towards custom properties, seems to me that whilst CSS in JS is the current React pattern, it'll likely be superseded by CSS Modules which are effectively vanilla CSS.

**Comment by jimdrury** [comment]
Hey @Tim-arts, 
just thought i'd let you know that with `0.2.0` you'll be able to theme the badges easier by passing in a `styles` object to the badge config. I'm just preparing the release now.

**Comment by Tim-arts** [comment]
That's great, I'm really looking forward to try it! Thank you for the simplification :)
