### ISSUE TITLE
Not usable in an Angular project

### ISSUE THREAD

**Issue by Tim-arts** [jimdrury/geometricpanda#24]
# 🐞 bug report

### Affected Package

 The issue is caused by package @geometricpanda/storybook-addon-badges

### Description

This package is not usable in an Angular project, I get this error:
> Cannot find module 'react-dom/package.json'

## 🔬 Minimal Reproduction

Generate a new angular app, and follow the steps described to add the badge addon into the app. Start the project and you'll get the error

## 🌍  Your Environment

**Storybook Version:**
<pre><code>6.3.8
</code></pre>

**@geometricpanda Version:**
<pre><code>0.0.4
</code></pre>

### How to fix it

It would need some tests but trying to add the "react-dom" package seems to fix the issue

**Comment by jimdrury** [comment]
Hey, 
I dont suppose you've got a github repo showing this have you?

Seems to be working great with Angular for me

**Comment by Tim-arts** [comment]
Sadly I don't have a repo but well that's weird because once I add this package into my repo, it shows up the error. Seems you don't have the same error on your end?

I actually succeeded to make it work by adding the react-dom dependency, I guess I'll live with it!
